server:
  port: 8085
logging:
  level:
    com: debug
spring:
  rabbitmq:
    host: 192.168.26.130  # 若应用在宿主机运行，使用宿主机 IP
    port: 5672          # AMQP 通信端口（非管理端口 15672）
    virtual-host: /hmall  # 与容器内创建的虚拟主机一致
    username: hmall
    password: 123456
    connection-timeout: 1s # 设置MQ的连接超时时间
    template:
      retry:
        enabled: true # 开启超时重试机制
        multiplier: 2 # 失败后下次的等待时长倍数，=initial-interval*multiplier
    publisher-confirm-type: correlated # 开启publisher confirm机制，并设置confirm类型
    publisher-returns: true # 开启publisher return机制